name: todo_app_firebase
description: Todo App with Firebase
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0 
  bloc: ^8.1.2
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  iconsax: ^0.0.8
  injectable: ^2.1.2
  intl: ^0.18.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/icons/
  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Medium.ttf
         - asset: assets/fonts/Inter-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 19