name: Build APK and Upload to Github Actions artifact

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.1'

      - run: flutter pub get

      # build APK
      - name: Build APK
        run: flutter build apk --flavor development --target lib/main_development.dart --release
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-development-release.apk